services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data/:/data
    deploy:
      resources:
        limits:
          cpus: '0.90'
          memory: 1.5g